from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import uvicorn
import os

# Load config
from app.config import OLLAMA_BASE_URL

from app.router import process_query_with_agents
from app.data_loader import get_retriever

# Initialize FastAPI app
app = FastAPI(
    title="Encoder Industrial Platform API",
    description="AI-powered multi-agent backend for RCA, Compliance, and Knowledge Copilot queries.",
    version="1.0.0"
)

# Allow frontend to communicate with this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the retriever once on startup
retriever = None

@app.on_event("startup")
async def startup_event():
    global retriever
    retriever = get_retriever()
    print("Vector store retriever initialized and ready.")

# Request schema
class QueryRequest(BaseModel):
    query: str
    agent_type: Optional[str] = None  # "RCA", "COMPLIANCE", or "COPILOT" — overrides auto-routing

# Response schema
class QueryResponse(BaseModel):
    agent: str
    response: str

@app.get("/")
def root():
    return {"status": "Encoder Industrial Platform API is running."}

# Metrics response schema
class MetricsResponse(BaseModel):
    uptime: float
    active_hypotheses: int
    outstanding_audits: int
    critical_gaps: int

@app.get("/metrics", response_model=MetricsResponse)
def get_metrics():
    """
    Returns platform KPI metrics for the dashboard overview.
    These are prototype values — replace with live telemetry data in production.
    """
    return MetricsResponse(
        uptime=94.7,
        active_hypotheses=3,
        outstanding_audits=7,
        critical_gaps=2
    )


@app.post("/query", response_model=QueryResponse)
async def query_agent(request: QueryRequest):
    """
    Main endpoint to process a user query.
    Routes to the specified agent (RCA, Compliance, or Copilot) when agent_type is provided,
    otherwise uses keyword-based auto-routing.
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    # Normalise agent_type: uppercase, strip whitespace, None if blank
    forced_agent = request.agent_type.strip().upper() if request.agent_type else None
    if forced_agent not in ("RCA", "COMPLIANCE", "COPILOT"):
        forced_agent = None

    try:
        # Retrieve relevant context from vector store
        docs = retriever.invoke(request.query)
        context = "\n\n".join([
            f"Source: {doc.metadata.get('source_file', 'Unknown')}\n{doc.page_content}"
            for doc in docs
        ])

        # Process through agent router, honouring forced agent type if set
        response = process_query_with_agents(
            query=request.query,
            context=context,
            forced_agent=forced_agent
        )

        # Fallback in case the model returns an empty string
        if not response or not response.strip():
            response = "I'm unable to generate a response at the moment. Please try again."

        agent_label = forced_agent.lower() if forced_agent else "auto-routed"
        return QueryResponse(agent=agent_label, response=response)

    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

import asyncio

class IngestResponse(BaseModel):
    message: str
    extracted_nodes: list
    extracted_links: list

@app.post("/ingest", response_model=IngestResponse)
async def ingest_document(file: UploadFile = File(...)):
    """
    Simulates OCR, parsing, and entity extraction of a heterogeneous document (e.g. PDF, P&ID).
    Returns a set of newly extracted nodes and relationships to be injected into the Knowledge Graph live.
    """
    # Simulate processing time (OCR, NLP chunking, LLM entity extraction)
    await asyncio.sleep(2.5)
    
    # In a real system, these would be dynamically generated by passing the file to the LLM.
    # We return mock extracted entities to prove the pipeline flow to the judges.
    filename = file.filename
    doc_id = filename.replace('.pdf', '').replace('.png', '').replace(' ', '_').lower()
    
    new_nodes = [
        {"id": doc_id, "group": "Document", "val": 8, "color": "#0d9488", "desc": f"Newly ingested document: {filename}"},
        {"id": "Valve V-102", "group": "Hardware", "val": 6, "color": "#334155", "desc": "Pressure relief valve identified in new document"},
        {"id": "OISD Clause 4.1", "group": "Document", "val": 7, "color": "#0d9488", "desc": "Regulatory compliance clause extracted"}
    ]
    
    new_links = [
        {"source": "Valve V-102", "target": doc_id, "label": "DOCUMENTED_IN"},
        {"source": "Valve V-102", "target": "Compressor St. 2", "label": "ATTACHED_TO"},
        {"source": doc_id, "target": "OISD Clause 4.1", "label": "REFERENCES"}
    ]
    
    return IngestResponse(
        message=f"Successfully ingested {filename} and extracted 3 entities.",
        extracted_nodes=new_nodes,
        extracted_links=new_links
    )

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    print(f"Starting Industrial Encoder RAG Backend on http://0.0.0.0:{port}")
    print(f"Swagger API Documentation available at http://localhost:{port}/docs")
    
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=port,
        reload=False
    )
